services:
  api:
    build: .
    container_name: assistant-api1
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    restart: always

  bot:
    build: .
    container_name: assistant-bot1
    command: poetry run python app/bot/main.py
    env_file:
      - .env
    depends_on:
      - api
      - postgres
    restart: always

  postgres:
    image: postgres:17
    container_name: assistant-postgres1
    env_file:
      - .env
    volumes:
      - assistant_postgres_data_v1:/var/lib/postgresql/data
    restart: always

volumes:
  assistant_postgres_data_v1:
