services:
  api:
    build: .
    command: sh -c "python scripts/wait_for_db.py && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    restart: always
    volumes:
      - .:/app

  bot:
    build: .
    command: python -m app.bot.main
    env_file:
      - .env
    environment:
      BOT_API_BASE_URL: http://api:8000
    depends_on:
      - api
      - postgres
    restart: always
    volumes:
      - .:/app

  postgres:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - assistant_postgres_data_v1:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    restart: always

volumes:
  assistant_postgres_data_v1:
