"""add hour and minute to reminders

Revision ID: e2e11d3937b9
Revises: 6d457b3347c0
Create Date: 2026-05-10 19:58:09.105571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e11d3937b9'
down_revision: Union[str, Sequence[str], None] = '6d457b3347c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'reminders',
        sa.Column(
            'hour',
            sa.Integer(),
            nullable=False,
            server_default='9',
        ),
    )

    op.add_column(
        'reminders',
        sa.Column(
            'minute',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )

    op.alter_column('reminders', 'hour', server_default=None)
    op.alter_column('reminders', 'minute', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'minute')
    op.drop_column('reminders', 'hour')
    # ### end Alembic commands ###
